#!/bin/bash

# 🚀 Quick Start Guide for Campus Rideshare
# Use this if the automated start-dev.sh has issues

echo "╔═══════════════════════════════════════════════════════════╗"
echo "║                                                           ║"
echo "║  🚀 Campus Rideshare - Manual Start Guide 🚀            ║"
echo "║                                                           ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""

# Step 1: PostgreSQL
echo "📊 STEP 1: Start PostgreSQL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run ONE of these commands:"
echo ""
echo "  # Using Homebrew services:"
echo "  brew services start postgresql@14"
echo ""
echo "  # OR using pg_ctl:"
echo "  pg_ctl -D /opt/homebrew/var/postgresql@14 start"
echo ""
echo "  # Check if running:"
echo "  brew services list | grep postgresql"
echo ""
read -p "Press ENTER after starting PostgreSQL..."
echo ""

# Step 2: Backend
echo "🔧 STEP 2: Start Backend"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Open a NEW terminal and run:"
echo ""
echo "  cd /Users/rajatsharma/Desktop/BTP/backend"
echo "  npm run dev"
echo ""
echo "Backend will start on: http://localhost:5000"
echo ""
read -p "Press ENTER after backend is running..."
echo ""

# Step 3: Frontend
echo "🎨 STEP 3: Start Frontend"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Open ANOTHER terminal and run:"
echo ""
echo "  cd /Users/rajatsharma/Desktop/BTP/frontend"
echo "  npm run dev"
echo ""
echo "Frontend will start on: http://localhost:3000"
echo ""
read -p "Press ENTER to see final instructions..."
echo ""

# Final
echo "✅ STEP 4: Test the Application"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Open browser: http://localhost:3000"
echo ""
echo "2. Test login:"
echo "   Phone: 1234567890 (any 10 digits)"
echo "   OTP: 123456"
echo ""
echo "3. Check backend health:"
echo "   http://localhost:5000/health"
echo ""
echo ""
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║                                                           ║"
echo "║  ✨ You're all set! Happy coding! ✨                     ║"
echo "║                                                           ║"
echo "╚═══════════════════════════════════════════════════════════╝"
